# User Settings | Edit there as per required

title: daniellimws
url: "https://daniellimws.github.io"
baseurl: ""

# This will show up at the top of index page
site_heading: >
    daniellimws

email: weesoong.lim@gmail.com
author: Daniel Lim Wee Soong
# This description will show up in google search results
# (for index page) etc.
description: >
    bunch of stuff here

# This will what will show against &copy; in the footer
copyright: daniellimws
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false         # Tip: Remove the span from site_heading if intro is set to true
# This will be displayed in your intro
short_bio: >
    Hello. I'm Daniel.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    Hi, I'm Daniel!

about_footer: true

twitter_username: daniellimws
github_username: daniellimws

favicon: true
favicon_location: "/images/favicon.ico"

profile_picture: images/profile.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-126247564-1 # GA Tracking ID

# Social Stuff | open graph and twitter cards
og_image: "images/profile.png" # This will show in facebook thumbnails
twitter_image: "images/profile.png" # This will show in twitter cards

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

plugins:
    - jekyll-paginate
    - jekyll-target-blank

sass:
    style: compressed
    sass_dir: _sass

collections:
    ctfs:
        output: "true"
    notes:
        output: "true"

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci

gems: [jekyll-paginate]